# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UfM55LJS1CE7lIraaWs_xYQ8QI4v7qVs
"""

import threading
input_string = ""

def input_thread():
  global input_string
  try:
    
    input_string = input("Enter a string: ")
  except Exception as e:
    print(e)
    return

def reverse_thread():
  global input_string
  reversed_string = input_string[::-1]
  print("Reversed string:", reversed_string)

def capital_thread():
  global input_string
  capitalized_string = input_string.upper()
  print("Capitalized string:", capitalized_string)

def shift_thread():
  global input_string
  shifted_string = ""
  for char in input_string:
    shifted_string += chr(ord(char) + 2)
  print("Shifted string:", shifted_string)

# Create the threads
input_t = threading.Thread(target=input_thread)
reverse_t = threading.Thread(target=reverse_thread)
capital_t = threading.Thread(target=capital_thread)
shift_t = threading.Thread(target=shift_thread)

input_t.start()
input_t.join()

reverse_t.start()
capital_t.start()
shift_t.start()

reverse_t.join()
capital_t.join()
shift_t.join()